version: '3.8'

services:
  ai-secretary:
    build: https://github.com/Kyroth88/ai-secretary.git#main
    container_name: ai_secretary
    restart: unless-stopped
    environment:
      - TZ=America/Toronto
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=gemini-2.0-flash
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS} #required google app password with no space! (e.g. abcdabcdabcdabcd)
      - IMAP_SERVER=imap.gmail.com
      - SMTP_SERVER=smtp.gmail.com
      - OBSIDIAN_TASKS_PATH=/vault/Tasks.md  # Changed to match /vault
    volumes:
      # Replace /your/actual/host/path with the real directory on your server
      - /your/actual/host/path:/vault
